### ISSUE TITLE
On use gets me a mimetype error

### ISSUE THREAD

**Issue by Arcanum417** [nvllsvm/jellysub#5]
```File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1097, in json raise ContentTypeError( aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://server/Artists/AlbumArtists?Recursive=true&StartIndex=0&Limit=10000')```

**Comment by nvllsvm** [comment]
Fixed in 0.0.6
